### ISSUE TITLE
Ability to configure blocklist-responses

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#10]
Today, the blocklist feature will respond with a NXDOMAIN when it hits one of the entries. I suggest the following additions:

- Return-Code NXDOMAIN (Default, and already available today)
- Return-Code REFUSED
- Return 0.0.0.0 (when A-Record) or 0::0 (when AAAA Record).
  - When not A or AAAA, revert to a default, e.g. one of the other responses, default would be NXDOMAIN
  - The IP's above would be defaults and should be configurable as well, so a "walled garden" setup would be possible
- A "NODATA" answer, meaning Return-Code NOERROR with an empty answer-section.
- Drop the request all together, no response.

**Comment by folbricht** [comment]
I'm wondering if that's overloading the functionality of the blocklist a bit. Configuring NXDOMAIN, REFUSED or NODATA responses would be fine. Dropping the response may work better for some listeners than others (thinking of DoH mainly). Some of the complexity comes from supporting the "hosts" format which already returns a suggested IP. So the default response would need to be nxdomain-unless-hosts-ip.

For the walled garden setup, how about I add one (or multiple) new groups that will respond with a fixed response. Then in combination with a router in front, that should achieve something similar and would be more flexible. Of course, routers are a bit slower at the moment, but I imagine that in most cases the walled garded would have a small number of "good" routes that are allowed out, with the default route pointing at a group that'll always respond with a fixed IP.

**Comment by cbuijs** [comment]
Having a group generating a response and able to point ot it would be great. I actually use the hosts file for that now when needed to walled-garden/spoof-IP thing, but for RCODES a separate group should be fine.

Also, maybe able to point to such groups when a blocklist is hit, so when NXDOMAIN no happens have the ability to point to mentioned/above groups.

**Comment by cbuijs** [comment]
I was thinking: If the router rules would have the ability to provide a hosts/regexp file for `source`, then an "end-node" group makes more sense, right? Then looping through the list of files would be more flexible.

It will solve the issue when mixing requests/responses groups where basically you cannot make a blocklisted entry into an allowlisted one after as well (bug? wae?)

For example, I want to block any requests that end into `194.109.0.0/16`, except if the query is for `.xs4all.nl`. Order doesn't matter (chaining group 1 to 2):

1. `blocklist-v2`: allowlist `.xs4all.nl` (Goes Through)
2. `blocklist-response-cidr`: blocklist `194.109.0.0/16` (Blocked)

Results in NXDOMAIN.

1. `blocklist-response-cidr`: blocklist `194.109.0.0/16` (Blocked)
2. `blocklist-v2`: allowlist `.xs4all.nl` (Is not detected, as packet contains NXDOMAIN of previous group)

Results in NXDOMAIN even when whitelisted, because of different groups and one is for request the other response.

Just some random thoughts and perhaps a corner case. Having the ability to point a resolver of a group when`allowlist` is hit is indeed easier/better/more-flexible.

**Comment by folbricht** [comment]
Been thinking about the static responder is best implemented. Came up with two options basically.

1) One component that can look at the query and based on the query type reply with a fixed response. This would be rather complex and it replicates parts of a router.

```toml
[groups.walled-garden]
type      = "static-responder"
responses = [
  {type = "A", answer = [{type =  "A", value="1.2.3.4"}]},
  {type = "MX", answer = [{type =  "MX", priority = 10, value="smtp.acme.test"}]},
  {type = "TXT", answer = []},
  {type = "AAAA", rcode = "refused"},
]
```

2) Every static responder is replying with just one kind of answer, regardless of the query and a router is used to send queries to the right responders. This is a little simpler, more flexible but requires more config as well.

```toml
[groups.static-a]
type   = "static-responder"
rcode = 0 # Response code: 0 = NOERROR, 1 = FORMERR, 2 = SERVFAIL, 3 = NXDOMAIN, ...
answer = [
  {type = "A", value="1.2.3.4"},
]

[groups.static-aaaa]
type   = "static-responder"
answer = [
  {type = "AAAA", value="::1"},
]

[groups.static-mx]
type   = "static-responder"
answer = [
  {type = "MX", priority = 10, value="smtp.acme.test"},
]

[groups.static-nxdomain]
type  = "static-responder"
rcode = 3

[routers.walled-garden-router]
routes = [
  { type = "A", resolver="static-a" },
  { type = "AAAA", resolver="static-aaaa" },
  { type = "MX", resolver="static-mx" },
  { resolver="static-nxdomain" }, # default route
]
```

Currently leaning towards option 2 to avoid the complexity and overlap with routers. Thoughts?

**Comment by cbuijs** [comment]
Yeah, option-2 has my vote too, more clear. Maybe a bit more config-work but that comes with flexibily. Not a showstopper in my book.

What happens within a static-responder if there is no match? It defaults to NXDOMAIN?

**Comment by folbricht** [comment]
Every responder returns the same thing, so the default is determined by which static responder the router sends the query to. The default route of the router handles the "no match"-case basically.

**Comment by cbuijs** [comment]
Gotcha, I get it now, was reading the example wrong (missed that the last one was a router). All makes sense to me.

**Comment by folbricht** [comment]
Take a look at the issue-10 branch. I think this implementation is the most flexible and it was simpler than expected since I could just use the existing parser for RRs. You basically define your response in zone-file format as in this example.

```toml
[groups.static-a]
type   = "static-responder"
rcode  = 0 # Response code: 0 = NOERROR, 1 = FORMERR, 2 = SERVFAIL, 3 = NXDOMAIN, ...
answer = ["IN A 1.2.3.4"]
ns = [
    "domain.com. 18000 IN NS ns1.domain.com.",
    "domain.com. 18000 IN NS ns2.domain.com.",
]
extra = [
    "ns1.domain.com. 1800 IN A 127.0.0.1",
    "ns1.domain.com. 1800 IN AAAA ::1",
    "ns2.domain.com. 1800 IN A 127.0.0.1",
    "ns2.domain.com. 1800 IN AAAA ::1",
]

[groups.static-aaaa]
type   = "static-responder"
answer = ["IN AAAA ::1"]

[groups.static-mx]
type   = "static-responder"
answer = ["IN MX 10 smtp.acme.test."]

[groups.static-nxdomain]
type  = "static-responder"
rcode = 3

# Use a router to send certain types of queries to static responders.
[routers.walled-garden-router]
routes = [
  { type = "A", resolver="static-a" },
  { type = "AAAA", resolver="static-aaaa" },
  { type = "MX", resolver="static-mx" },
  { resolver="static-nxdomain" }, # default route
]
```

Now, this will not allow dropping queries without a response. For this to work I need to update a few things first.
