### ISSUE TITLE
Block based on responses

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#11]
Today, the blocklist feature works by blocking based on the query-name, it would be great to block on responses (take all records in RRSET into account) as well:

- Block based on IP-Address in an A/AAAA records, blocklist should accept CIDR's
- Block based on domain-name (as used in CNAME, NS, SOA, MX etc)
- Block based on Regex which would match the response data
  - Ignore any weight, priorities or other parameters and only use the last field of a response

**Comment by folbricht** [comment]
What did you have in mind for blocking on regex? What piece of the response would the regex be on, any data in CNAME, TXT, etc responses?

**Comment by cbuijs** [comment]
Basically (in my view):

- A/AAAA the IP-Address (New blocking type, CIDR).
- CNAME/MX/NS/PTR/SRV - The domain used (last value of data), Regex or Domain type blocking.
- The rest (or all): No response checking, but if done/needed, regex based on whole data.

There is also an option needed to specify to only check the data of the first record of the rrset, or against any.

**Comment by folbricht** [comment]
Going to break those up into individual group entities to keep the configuration complexity down. So perhaps a `cidr-response-block` which works on CIDR and a `response-blocklist` which looks for all the string responses. Later maybe one that filters on properties.

These could then be chained in the configuration to get the same effect. And ordering them in config would allow for prioritization.

**Comment by folbricht** [comment]
A first implementation of `response-blocklist-cidr` exists on https://github.com/folbricht/routedns/tree/issue-11 now. It supports blocking of responses based on IPs in A or AAAA records. The configuration is similar to blocklist-v2. It supports a local static list in config, as well reading from files or HTTP with refresh period.

Simple, fixed config:
```toml
[groups.cloudflare-blocklist]
type                = "response-blocklist-cidr"
resolvers           = ["cloudflare-dot"]
blocklist           = [
  '127.0.0.0/24',
  '157.240.0.0/16',
]
```

Multiple blocklists read from files or URLs.
```toml
[groups.cloudflare-blocklist]
type              = "response-blocklist-cidr"
resolvers         = ["cloudflare-dot"]
blocklist-refresh = 86400
blocklist-source  = [
  {source = "./example-config/cidr.txt"},
]
```

Do you happen to have an example URL that has a list of CIDR addresses I can use in config examples?

**Comment by folbricht** [comment]
And now there's also `response-blocklist-name` which filters on the strings in NS, MX, CNAME, PTR and SRV records. The format again is very similar to a regular blocklist with static, local and remote lists and multiple formats.

```toml
 [groups.cloudflare-blocklist]
type             = "response-blocklist-name"
resolvers        = ["cloudflare-dot"]
blocklist-format = "domain"
blocklist        = [
  'ns.evil.com',
  '*.acme.test',
]
```

And the same for remote:
```toml
[groups.cloudflare-blocklist]
type              = "response-blocklist-name"
resolvers         = ["cloudflare-dot"]
blocklist-refresh = 86400
blocklist-source  = [
  {format = "domain", source = "./example-config/domains.txt"},
]
```

**Comment by cbuijs** [comment]
Example CIDR Lists you can use:

```
https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/plain.black.ip4cidr.list
https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/plain.black.ip6cidr.list
```
Will try to test today/tomorrow and let you know.

**Comment by folbricht** [comment]
This seems to load fine for me, note that it's called `blocklist-source` and then every item has a `source` property under it. Don't think the 2 IP4 examples are actually in the list. Trying to find some but no luck yet.

```toml
[groups.cloudflare-blocklist]
type              = "response-blocklist-cidr"
resolvers         = ["cloudflare-dot"]
blocklist-refresh = 86400
blocklist-source  = [
  {source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/plain.black.ip4cidr.list"},
  {source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/plain.black.ip6cidr.list"},
]
```

Since it's a very simple algorithm at the moment (linear scan), it'll add several milliseconds to the query. Didn't have time to implement a full routing table lookup algorithm yet, but that'll come.

Right now, the CIDR blocklist queries every RR in the Answer section only. Should probably add the Extra records as well. You were also asking to have a flag to only make it look at the first one, that's not yet there but easy to add.
