### ISSUE TITLE
Support DNS-over-QUIC

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#12]
Future feature, just as a heads-up.

See:
https://tools.ietf.org/id/draft-huitema-quic-dnsoquic-06.html
https://github.com/ns1/doq-proxy

**Comment by folbricht** [comment]
The issue-12 branch has a first implementation of this. As usual, both directions, server and client are supported, but haven't had any luck finding a public server that supports DoQ. But it's able to talk DoQ to itself at least like in this example using two routedns processes on localhost.

Simple DoQ server/listener, forwarding anything received over DoT:
```toml
[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[listeners.local-doq]
address = ":1784"
protocol = "doq"
resolver = "cloudflare-dot"
server-crt = "example-config/server.crt"
server-key = "example-config/server.key"
```

Client DoQ implementation, receiving over plain DNS and forwarding via DoQ:
```toml
[resolvers.local-doq]
address = "server.acme.test:1784"
protocol = "doq"
ca = "example-config/server.crt"
bootstrap-address = "127.0.0.1"

[listeners.local-udp]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "local-doq"
```
