### ISSUE TITLE
A "allow" feature to override blacklisted domains

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#13]
Hi,

I am having issues blocking (or any parent domain):
`*.me.`

but remain having access/resolution to:
`*.tikkie.me.`

Missing an "exclude", "allow" feature which takes precedence over a "blocked" would be great to allow these kind of cases. Maybe a "skip" feature (don't go to blocklist when hit).

Cheers!
-Chris

**Comment by folbricht** [comment]
Thinking of supporting something like an allowlist that takes precedence and uses the same format as the blocklist items, but without the ability to load it from a file or remote server. Though that's doable too if necessary.

**Comment by cbuijs** [comment]
Having the ability to use file/url is necessary, but kicking it off just by config would be a nice appetizer :-).

**Comment by folbricht** [comment]
There's now a first cut of this on the issue-13 branch (https://github.com/folbricht/routedns/tree/issue-13). It's still missing docs and very little testing has been done so far. It supports the same options as the blocklist, just that everything is prefixed with `allowlist-`. A remote config looks like this:

```toml
[groups.cloudflare-blocklist]
type = "blocklist"
resolvers = ["cloudflare-dot"]
format    = "regexp"
source    = "https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/routedns.regexp.list"
refresh   = 86400
allowlist-format  = "domain"
allowlist-source  = "https://some.other.list"
allowlist-refresh = 86400
```

**Comment by cbuijs** [comment]
Just occurred to me, testing this. You might need a more holistic approach for this.

Especially when using multiple sources. You might want 10 blacklists pulled from the internet, and 3 whitelists ones. Where you want to use it consolidated. E.g. a whitelist entry works against any blacklist-entry. Now you have to chain groups to make that happen loosing that effect.
Or just whitelist one domain against 10 blacklist-domains.

Multiple "source" statements would fix this, I was thinking to include the type into the beginning of the source-name, so it could be specified like this:

```
[groups.my-resolver]
type = "blocklist"
resolvers = ["doh-google"]
source = "regexp:/opt/accomplist/deugniets/routedns.black.regexp.list"
source = "domain:https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/routedns.black.domain.list"
allowlist-source = "domain:https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/routedns.white.domain.list"
```
Maybe too complex and will break backwards compatibility.

**Comment by folbricht** [comment]
Yes, it'd break backwards compatibility. Though could implement a new element "multi-blocklist" and treat the regular blocklist as a special case of that. Need to think a bit more about it. It's easy to do in code, but as usual getting configuration right is tricky.

**Comment by folbricht** [comment]
Since this hasn't yet been merged, I'm reworking this into an `advanced-blocklist` that'll allow multiple sources while preserving the `blocklist` for backwards-compatibility. Error handling during refresh could get interesting. Likely going to treat any error from a refresh as a refresh-failure and stick with the old list.

**Comment by cbuijs** [comment]
On the refresh, you might want to keep "last successful fetched" version somewhere, so when fetching fails, that one stays in effect and only gets replaced after a good fetch. Might only be needed on URL version?

**Comment by folbricht** [comment]
Implemented a new `blocklist-v2` to support multiple block and allow-lists of different types. The config looks like this:
```toml
[groups.cloudflare-blocklist]
type = "blocklist-v2"
resolvers = ["cloudflare-dot"]
blocklist-refresh = 86400
blocklist-source = [
   {format = "regexp", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/routedns.regexp.list"},
]
allowlist-refresh = 86400
allowlist-source = [
   {format = "regexp", source = "https://some.allow/list"},
   {format = "domain", source = "example-config/domains.txt"},
]
```
Tried a couple of formats but nothing large-scale yet. And docs are still to-do as well. Please let me know if I missed anything or if there are any issues.
