### ISSUE TITLE
Couldn't get the mTLS config Up and Running

### ISSUE THREAD

**Issue by galpt** [folbricht/routedns#130]
Hello,

We've tried to use mTLS for both server & client but it didn't work.
These are some of the errors:
```
time="2021-02-14T23:25:22+07:00" level=info msg="starting listener" addr=":53" id=udp protocol=udp
time="2021-02-14T23:25:22+07:00" level=info msg="starting listener" addr=":53" id=tcp protocol=tcp
time="2021-02-14T23:25:22+07:00" level=info msg="starting listener" addr=":443" id=dohq protocol=doh
time="2021-02-14T23:25:26+07:00" level=error msg="failed to resolve" addr=":53" client=127.0.0.1 error="Get \"https://galpt.xyz:443/dns-query?dns=9D8BAAABAAAAAAAAA3d3dwpnb29nbGVhcGlzA2NvbQAAAQAB\": CRYPTO_ERROR (0x12a): tls: bad certificate" id=udp protocol=udp qname=www.googleapis.com.
time="2021-02-14T23:25:26+07:00" level=error msg="failed to resolve" addr=":53" client=127.0.0.1 error="Get \"https://galpt.xyz:443/dns-query?dns=gIQBAAABAAAAAAAACGFjY291bnRzBmdvb2dsZQNjb20AAAEAAQ\": CRYPTO_ERROR (0x12a): tls: bad certificate" id=udp protocol=udp qname=accounts.google.com.
```

The certificate files are valid from trusted Certificate Authorities and they're working just fine with the `mutual-tls = false` option but gives errors when changed to `true`.
Is there any other way to bypass this? Perhaps adding `&tls.Config{InsecureSkipVerify: true}` or something similar.

**Comment by folbricht** [comment]
Could you show me the config you're using? Feel free to remove any sensitive filenames of course.

When you say "trusted CA" do you mean it's a public CA? That would be rather unusual with mTLS. It can be made to work, but got to be careful to not accidentally allowing any customer of that public CA to connect to your service. But let's see what the config is first.

**Comment by galpt** [comment]
A lot of things added to our config but for this problem might be something like this (simplified):
```
######## Upstream Resolvers ########
[resolvers.google-quic]
address = "https://dns.google/dns-query"
protocol = "doh"
transport = "quic"
bootstrap-address = "8.8.8.8"

######## DoHQ Listeners ########
[listeners.dohq]
address = ":443"
protocol = "doh"
transport = "quic"
resolver = "google-quic"
server-crt = "galptServerCert.pem"
server-key = "galptServerKey.pem"
ca = "galptServerCArootCert.pem"
mutual-tls = false
frontend = { trusted-proxy = "0.0.0.0/0" }

[resolvers.resolvedohq]
address = "https://galpt.xyz:443/dns-query"
protocol = "doh"
transport = "quic"
ca = "galptServerCArootCert.pem"
client-crt = "galptClientCert.pem"
client-key = "galptClientKey.pem"
bootstrap-address = "127.0.0.1"

[groups.multidohq]
type = "fastest"
resolvers = ["resolvedohq"]

######## UDP/TCP Listeners ########
[listeners.udp]
address = ":53"
protocol = "udp"
resolver = "multidohq"

[listeners.tcp]
address = ":53"
protocol = "tcp"
resolver = "multidohq"
```

We used to have several DoHQ listeners before but now we're just using one and decided to leave the `[groups.multidohq]` there just in case we might need it in the future.

The config works well if we set mutual-tls = false but went wrong when set to true.
The CA we're using is **Cloudflare's Advanced Certificate Manager** and the Certificate Authority is **DigiCert**.
mTLS has been enabled of course.

**Comment by folbricht** [comment]
Just tried it here with a simplified config and test certificates

Server:
```toml
[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[listeners.local-doh]
address = ":8443"
protocol = "doh"
transport = "quic"
resolver = "cloudflare-dot"
server-crt = "../../testdata/server.crt"
server-key = "../../testdata/server.key"
ca = "../../testdata/ca.crt"
mutual-tls = true
```

Client:
```toml
[resolvers.myserver-doh]
address = "https://127.0.0.1:8443/dns-query"
protocol = "doh"
transport = "quic"
ca = "../../testdata/ca.crt"
client-crt = "../../testdata/client.crt"
client-key = "../../testdata/client.key"

[listeners.local]
address = ":1153"
protocol = "udp"
resolver = "myserver-doh"
```

It works as expected, you can test it out the certificates here: https://github.com/folbricht/routedns/tree/master/testdata to make sure your config is otherwise correct.

This looks very much like your client certificates are not quite right. They may have some usage restrictions, like saying they can only be used as server certs perhaps. Regardless, using client certs signed by a public CA probably doesn't do what you want it to. What's your goal? Only allowing valid clients to connect to your server? In that case you probably want to use your own CA for the client certificate (and configure that as `ca=` in the server-config).
