### ISSUE TITLE
Access-Lists to block or/and allow particular DNS Clients

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#14]
Subject says it all, a feature (on "listener") to specify which DNS Clients (by IP-Address/CIDR) that are either allowed or not allowed to send queries.

Check BIND's allow-query as an example:
https://www.zytrax.com/books/dns/ch7/queries.html#allow-query

**Comment by folbricht** [comment]
Does BIND just drop the queries or respond with an error in this case?

**Comment by cbuijs** [comment]
It responds with a rcode REFUSED when not listen in ACL.

**Comment by folbricht** [comment]
PR is open from branch https://github.com/folbricht/routedns/tree/issue-14. This supports a `allowed-net` option on all listeners.

```toml
[listeners.local-udp]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "cloudflare-dot"
allowed-net = ["127.0.0.1/32", "::1/128", "192.168.0.0/16"]
```
