### ISSUE TITLE
Influence size and lifetime of cached entries

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#18]
Ability on a cache group to specify the following:

- min-ttl: Minimal-ttl, records are at least cached for this time, "0" will use the default (soa/lowest or 60 seconds as is now)
- max-ttl: Maximum-ttl, records do not stay longer then this in cache and will be renewed after expired, "0" will not cap ttl and use the TTL given.
- max-size: Maximum number of entries in cache, when reached, oldest records should be expunged

See this reference-article by having minimal-ttl set to 2400 seconds as good measure:
https://blog.apnic.net/2019/11/12/stop-using-ridiculously-low-dns-ttls

**Comment by folbricht** [comment]
The first two are very simple, the last one (max-size) needs a bit more work.

**Comment by cbuijs** [comment]
Maybe to add: Have sepperate config-options for negative responses (other then RCODE=NOERROR). There is already something in place with 60 seconds when no SOA I believe whioch could be extended/overwritten accoding config. I would suggest the same max/min type of config-items as above.

**Comment by folbricht** [comment]
There's now an implementation on the issue-18 branch that supports limiting the size of the cache as well as setting TTL of responses without SOA.

```toml
[groups.cloudflare-cached]
type = "cache"
resolvers = ["cloudflare-dot"]
cache-size = 1000               # Optional, max number of responses to cache. Default unlimited
cache-negative-ttl = 3600       # Optional, TTL to apply to responses without a SOA
```
Please let me know if you see anything wrong with it.

Wrt to the TTL changes, max/min, to stick with flexibility I'm going to add a new `ttl-modifier` group that can apply the limits. That way it's not limited to just the cache. You can put that anywhere in the pipeline, even un-cached pipelines. In most cases though, you'd put that after the cache so they work together.

**Comment by folbricht** [comment]
Added the `ttl-modifier` as well (same branch). You can combine it with a cache like so:

```toml
[groups.cloudflare-updated-ttl]
type = "ttl-modifier"
resolvers = ["cloudflare-dot"]
ttl-min = 3600
ttl-max = 86400

[groups.cloudflare-cached]
type = "cache"
resolvers = ["cloudflare-updated-ttl"]
```
