### ISSUE TITLE
Feature-Request: DoH without TLS

### ISSUE THREAD

**Issue by brotaxt** [folbricht/routedns#214]
Hey guys, 

I couldn't get the doh server running. It only works if I specify any additional protocol. quic for example.

Any suggestions/tips? 

```
root@localhost:~/routedns/routedns/cmd/routedns/example-config# /opt/routedns/routedns /opt/routedns/config.toml
INFO[0000] starting listener                             addr="[::1]:8053" id=local-doh-behind-proxy protocol=doh
ERRO[0000] listener failed                               error="open : no such file or directory"
```

```
root@localhost:~/routedns/routedns/cmd/routedns/example-config# cat /opt/routedns/config.toml  |grep -v '#'

title = "RouteDNS configuration"

[resolvers]

  [resolvers.dnsmasq]
  address = "127.0.0.1:53"
  protocol = "udp"


[groups]

  [groups.local_resolver]
  type = "cache"



[listeners]


  [listeners.local-doh-behind-proxy]
  address = "[::1]:8053"
  protocol = "doh"
  resolver = "local_resolver"
  doh = { method = "GET" }
  frontend = { trusted-proxy = "127.0.0.1/24" }

```

**Comment by folbricht** [comment]
Since that's TLS server, it expects a cert and key. The error message isn't great, it's complaining about not being able to open the certificate with empty name basically.

This should work, added the `server-crt` and `server-key` keys. Also added `resolvers =` to the cache which was missing.
```toml
title = "RouteDNS configuration"

[resolvers]

  [resolvers.dnsmasq]
  address = "127.0.0.1:53"
  protocol = "udp"

[groups]

  [groups.local_resolver]
  type = "cache"
  resolvers = ["dnsmasq"]

[listeners]

  [listeners.local-doh-behind-proxy]
  address = "[::1]:8053"
  protocol = "doh"
  resolver = "local_resolver"
  server-crt = "example-config/server.crt"
  server-key = "example-config/server.key"
  doh = { method = "GET" }
  frontend = { trusted-proxy = "127.0.0.1/24" }
```

**Comment by brotaxt** [comment]
Thank you very much for the quick response. The error message was a bit misleading. 
Is it possible to run the doh-server without TLS encryption? (http) as my nginx already does https for the clients.

Best regards

**Comment by folbricht** [comment]
Hmm, DoH without TLS? Should be possible, but that's not exactly secure. If we do that, we'd have to find a way to make sure users don't accidentally run in this mode thinking it's encrypted

**Comment by brotaxt** [comment]
A possible solution could be an extra parameter which needs to be set to activate the unencrypted http mode!?

Unfortunately I have no knowledge of go programming but I'm glad to help with testing, providing logs and so on.

**Comment by brotaxt** [comment]
@folbricht, do you think that could be implemented in the near future? :)

**Comment by folbricht** [comment]
Took a quick look and it's quite easy to do. Should be able to get that in this weekend. Just short on time at the moment, but this is doable, especially if you're willing to test it.

**Comment by brotaxt** [comment]
Wow, thanks for the quick response! :) Unfortunately I'm not familiar with go programming, so I couldn't help you with that. But I would be glad to support you with testing.

**Comment by folbricht** [comment]
There's now a draft of this on the issue-214 branch which introduces a "no-tls = true" option on the DoH listener, but only for TCP. The quic library requires a valid TLS config. Disabling TLS looks like this
```toml
[listeners.local-doh]
address = ":8080"
protocol = "doh"
resolver = "cloudflare-dot"
no-tls = true
```
I haven't done any testing yet, other than making sure the server starts up.
