### ISSUE TITLE
Feature-Request: Logging to Syslog

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#231]
Having the option to log to Syslog would be nice.

**Comment by folbricht** [comment]
That's a good idea. Now, there's really two ways to do that:

1) Just send everything that's currently going to STDOUT to syslog as well. This would require updating the logger we use (I believe it supports syslog already).
2) Build an element for syslog that can then be placed anywhere in the chain to log requests that fly by. There could be more than one in this case

Which of these did you have in mind?

**Comment by cbuijs** [comment]
I like #2 way better as it is both in line how everything works, and gives control to the user.

Maybe a command-line switch to enable #1, so maybe the messages not from elements can be logged as well? Like errors and debug?

**Comment by charlieporth1** [comment]
If you create a systemd unit you can create a syslog interpreter that will make log to syslog. Unless you're just trying to run it from the command line and have it run into the syslog

**Comment by folbricht** [comment]
There's a draft implementation in https://github.com/folbricht/routedns/pull/233

The config looks like this:
```toml
[groups.cloudflare-logged]
type = "syslog"
resolvers = ["cloudflare-dot"]
network = "udp" # "udp", "tcp", "unix"
address = "192.168.0.1:514" # Defaults to the local syslog server
priority = "info" # "emergency", "alert", "critical", "error", "warning", "notice", "info", "debug"
tag = "routedns"
```
Only done casual testing on it so far.

So this implements 2) which is more flexible. Could be used to log certain queries from the pipeline, like those on a blocklist or similar. As @charlieporth1 suggested, getting the normal logs out of routedns could be done with systemd.
