### ISSUE TITLE
Router mode supports loading from disk

### ISSUE THREAD

**Issue by liang-hiwin** [folbricht/routedns#261]
Router

Configuration:

[routers.router1]
routes = [
  { name = '(^|\.)google\.com\.$', types = ["A", "AAAA", "MX"], resolver="google-udp" },
 { name = '(^|\.)youtube\.com\.$', types = ["A", "AAAA", "MX"], resolver="quad9-udp" },
 ............. #many domain names
  { resolver="cloudflare-dot" }, # default route
]

When more than 500 lines are added here, routedns cannot be started or when the program can start the program, it cannot be used normally, and no parsing can be performed at this moment.

**Comment by liang-hiwin** [comment]
It is recommended to change to something like this to read the list

[routers.router1]
routes = [
{ file = "/path/to/google_domain.list", types = ["A", "AAAA", "MX"], resolver="google_udp" },
{ file = "/path/to/youtube_domain.list", types = ["A", "AAAA", "MX"], resolver="quad9_udp" },
{ file = "/path/to/github_domain.list", types = ["A", "AAAA", "MX"], resolver="opendns_udp" },
............. #many domain names
{ resolver="cloudflare_dot" }, # default route
]



**The content of google_domain.list is one domain name per line,**

1. When filling in a single string, such as google.com, it will match "google.com", "google.com.hk" and "www.google.com", but not "google.cn".

2. When filling in a string starting with "domain:", such as doamin:google.com, it matches "www.google.com", "google.com", but does not match "adsgoogle.com"

3. When filling in a string starting with "full:", such as full:google.com, it matches "google.com", but does not match "www.google.com"

4. When filling in a string starting with "regexp:", such as regexp:google\.com$, the matching method fully supports go regexp syntax

**Comment by folbricht** [comment]
Routers use regexp which are less efficient, though I would still expect it work work (not tested with 500 rules yet). From your example it doesn't look like you need a regex list. To achieve the same thing without regex, you can use a blocklist. It'll let you define a large list of domain names and give you a resolver for everything that matches the list, and one for everything else.

**Comment by liang-hiwin** [comment]
> Routers use regexp which are less efficient, though I would still expect it work work (not tested with 500 rules yet). From your example it doesn't look like you need a regex list. To achieve the same thing without regex, you can use a blocklist. It'll let you define a large list of domain names and give you a resolver for everything that matches the list, and one for everything else.

I test your method ,  thanks

**Comment by liang-hiwin** [comment]
@folbricht 

Can resolvers add sock5 proxy mode

```
[resolvers.cloudflare-dot-1]
address = "1.1.1.1:853"
protocol = "dot"
sock5 = "127.0.0.1:1080"   

 ######1.1.1.1:853 All traffic is forwarded by the sock5 proxy, which can avoid use when 1.1.1.1 is blocked by the firewall
```

**Comment by liang-hiwin** [comment]
> Routers use regexp which are less efficient, though I would still expect it work work (not tested with 500 rules yet). From your example it doesn't look like you need a regex list. To achieve the same thing without regex, you can use a blocklist. It'll let you define a large list of domain names and give you a resolver for everything that matches the list, and one for everything else.

Response Blocklist -> resolvers - Array of upstream resolvers, only one is supported. Only one can be filled in the upstream of the list. How to define a domain name resolver that is not in the list?

**Comment by folbricht** [comment]
There is a `blocklist-resolver` option you can use. All matches will be sent to that. See https://github.com/folbricht/routedns/blob/master/doc/configuration.md#Query-Blocklist

**Comment by liang-hiwin** [comment]
> There is a `blocklist-resolver` option you can use. All matches will be sent to that. See https://github.com/folbricht/routedns/blob/master/doc/configuration.md#Query-Blocklist

**Can an input format like this be added?**
```
[groups.alldns]
type = "blocklist-v2"
resolvers = ["random"]
blocklist-refresh = 30
blocklist-source = [
   {format = "hosts", source = "/opt/routedns/hosts.txt"},
]

allowlist-resolver = "google_domain"
allowlist-refresh = 30
allowlist-source = [
   {format = "domain", source = "/opt/routedns/google_list.txt"},
]


##############unsupported input format

allowlist-resolver = "youtube_domain"
allowlist-refresh = 30
allowlist-source = [
   {format = "domain", source = "/opt/routedns/youtube_list.txt"},
]

################unsupported input format

```

**Comment by folbricht** [comment]
You can't repeat the same properties in one group. So things like `allowlist-source` can only exist once, but you can define multiple lists, so something like this should work:
```toml
allowlist-resolver = "google_domain"
allowlist-refresh = 30
allowlist-source = [
   {format = "domain", source = "/opt/routedns/google_list.txt"},
   {format = "domain", source = "/opt/routedns/youtube_list.txt"},
]
```

If you want to break this up and have different allowlist-resolvers per list, you'll need to chain a couple of blocklistv2, each with a different allowlist

**Comment by liang-hiwin** [comment]
> "random"]
> blocklist-refresh = 30
> blocklist-source = [
>    {format = "hosts", source = "/opt/routedns/hosts.txt"},
> ]

How to connect two blocklist-v2, I'm a little confused。

```
[groups.alldns]
type = "blocklist-v2"
resolvers = ["youtube_dns"]
blocklist-refresh = 30
blocklist-source = [
   {format = "hosts", source = "/opt/routedns/hosts.txt"},
]

allowlist-resolver = "google_domain"
allowlist-refresh = 30
allowlist-source = [
   {format = "domain", source = "/opt/routedns/google_list.txt"},
]

[groups.youtube_dns]
type = "blocklist-v2"
resolvers = ["random"]
allowlist-resolver = "youtube_domain"
allowlist-refresh = 30
allowlist-source = [
   {format = "domain", source = "/opt/routedns/youtube_list.txt"},
]
```

**Comment by folbricht** [comment]
It's actually much simpler. You don't even need to use the allowlists if all you want to do is categorize queries and route them separately

```toml
[groups.youtube]
type = "blocklist-v2"
resolvers = ["microsoft"] # Forward all non-matches to the next splitter
blocklist-resolver = "youtube-resolver" # This is where all matches (youtube traffic) are routed
blocklist-refresh = 30
blocklist-source = [
   {format = "hosts", source = "/opt/routedns/youtube.txt"}, # This list contains all YT domains
]

[groups.microsoft]
type = "blocklist-v2"
resolvers = ["upstream"] # Forward all non-matches to the next resolver
blocklist-resolver = "microsoft-resolver" # This is where all matches (microsoft traffic) are routed
blocklist-refresh = 30
blocklist-source = [
   {format = "hosts", source = "/opt/routedns/microsoft.txt"}, # This list contains all microsoft domains
]
```

**Comment by folbricht** [comment]
It's actually much simpler. You don't even need to use the allowlists if all you want to do is categorize queries and route them separately. Something like this.

```toml
[groups.youtube]
type = "blocklist-v2"
resolvers = ["microsoft"] # Forward all non-matches to the next splitter
blocklist-resolver = "youtube-resolver" # This is where all matches (youtube traffic) are routed
blocklist-refresh = 30
blocklist-source = [
   {format = "hosts", source = "/opt/routedns/youtube.txt"}, # This list contains all YT domains
]

[groups.microsoft]
type = "blocklist-v2"
resolvers = ["upstream"] # Forward all non-matches to the next resolver
blocklist-resolver = "microsoft-resolver" # This is where all matches (microsoft traffic) are routed
blocklist-refresh = 30
blocklist-source = [
   {format = "hosts", source = "/opt/routedns/microsoft.txt"}, # This list contains all microsoft domains
]
```

There are other ways but this is quite straightforward

**Comment by cbuijs** [comment]
Should `formats` not be `domains`?

**Comment by liang-hiwin** [comment]
> Should `formats` not be `domains`?

domain is true

**Comment by pmeiyu** [comment]
> Routers use regexp which are less efficient, though I would still expect it work work (not tested with 500 rules yet). From your example it doesn't look like you need a regex list. To achieve the same thing without regex, you can use a blocklist. It'll let you define a large list of domain names and give you a resolver for everything that matches the list, and one for everything else.

@folbricht I want to route 1000 domains to resolver A, another 1000 domains to resolver B, another 1000 domains to resolver C, another 1000 domains to resolver D. But blocklist-v2 can have only three resolvers (default, allow, block).  Is there an easy solution apart from chaining several blocklist-v2 together?  It would be great if router mode supports easily specifying thousands of domains in a route, either in a file or in a list, like blocklist-v2 format.

**Comment by folbricht** [comment]
There isn't currently anything like that available. Chained blocklists is likely the fastest solution. But you can also use a router with a ton of routes, though if this gets very long, let's says 10s or 100s of thousands it'll slow things down during querying since it treats them as regex and evaluates all in order. To keep the config readable, you can break out the router config into a separate file as per https://github.com/folbricht/routedns/blob/master/doc/configuration.md#Split-Configuration 

If you see an issue with routedns having issues with a that let me know. The original comment in this thread suggested a limit of around 500 but I can't reproduce that. Even with 2k routes the startup time isn't impacted at all for me.

**Comment by folbricht** [comment]
Closing this, since the approach suggested in the thread covers it and you confirmed it worked.

A `blocklist-v2` group loads a large list of domain names from a file and sends matches to one resolver and everything else to another, which is routing rather than blocking when `blocklist-resolver` is set. Chaining one group per list gives the three destinations from your example:

```toml
[groups.route-google]
type              = "blocklist-v2"
resolvers         = ["route-youtube"]   # everything that does not match, on to the next list
blocklist-resolver = "google-udp"       # everything that matches
blocklist-source  = [
  {format = "domain-subdomain", source = "/path/to/google_domain.list"},
]

[groups.route-youtube]
type              = "blocklist-v2"
resolvers         = ["cloudflare-dot"]  # the default route
blocklist-resolver = "quad9-udp"
blocklist-source  = [
  {format = "domain-subdomain", source = "/path/to/youtube_domain.list"},
]
```

The list formats line up with most of what you described. `domain-subdomain` treats a bare `google.com` as the apex plus all sub-domains, which is your `domain:` prefix. `domain` matches a bare entry exactly, which is your `full:` prefix, and also supports `.google.com` for apex plus sub-domains and `*.google.com` for sub-domains only. A separate source with `format = "regexp"` covers your `regexp:` prefix. Lists are matched with a trie rather than by evaluating regular expressions in order, so the size of the list is not the problem it would be in a router.

The one mode without an equivalent is a bare entry matching `google.com.hk`, which is a substring match specific to the v2ray format. `.google.com` is the closest, and it does not match a different registered domain that happens to start with the same string.

`blocklist-refresh` reloads the files on an interval if they change on disk.
