### ISSUE TITLE
The Cache Shuffle or Minimizer breaks cname chains.

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#336]
Since the latest patches/updates, something changed with the `collapser`.

Using google:
```
dig @8.8.8.8 www.paypal.com

; <<>> DiG 9.10.6 <<>> @8.8.8.8 www.paypal.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 169
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.paypal.com.			IN	A

;; ANSWER SECTION:
www.paypal.com.		1902	IN	CNAME	www.glb.paypal.com.
www.glb.paypal.com.	169	IN	CNAME	paypal-dynamic.map.fastly.net.
paypal-dynamic.map.fastly.net. 169 IN	A	151.101.1.21
paypal-dynamic.map.fastly.net. 169 IN	A	151.101.65.21
paypal-dynamic.map.fastly.net. 169 IN	A	151.101.129.21
paypal-dynamic.map.fastly.net. 169 IN	A	151.101.193.21

;; Query time: 59 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Sep 11 11:54:53 CEST 2023
;; MSG SIZE  rcvd: 172
```

With routedns, cache, collapse and minimizer:
```
dig @127.0.0.1 www.paypal.com

; <<>> DiG 9.10.6 <<>> @127.0.0.1 www.paypal.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59461
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.paypal.com.			IN	A

;; ANSWER SECTION:
www.paypal.com.		57	IN	CNAME	www.glb.paypal.com.
www.glb.paypal.com.	57	IN	CNAME	paypal-dynamic.map.fastly.net.
paypal-dynamic.map.fastly.net. 57 IN	A	151.101.37.21

;; Query time: 20 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Sep 11 11:55:27 CEST 2023
;; MSG SIZE  rcvd: 124
```
The output should be only contain the IP-Addresses and no CNAME entries, it misses 3 of the original IPs.

**Comment by folbricht** [comment]
Based on the implementation of the minimizer it only removes Extra and NS records, doesn't actually touch the answer records. Did you mean the `response-collapse` element? That one should strip CNAMEs out.

As for the missing answer records, that seems to be a bug and I'll try to repro+fix that.

**Comment by folbricht** [comment]
Which order did you chain those in your config, I've tried:
- listener -> collapse -> minimize -> cache -> resolver
- listener ->minimize -> cache ->  collapse -> resolver
And can't repro it yet

**Comment by folbricht** [comment]
Do you see it with a config like this as well?

```toml
[listeners.local-udp]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "minimize"

[groups.minimize]
type = "response-minimize"
resolvers = ["collapse"]

[groups.collapse]
type = "response-collapse"
resolvers = ["cache"]

[groups.cache]
type = "cache"
resolvers = ["google-dot"]
cache-negative-ttl = 10
cache-answer-shuffle = "round-robin"
backend = {type = "memory", size = 1000}

[resolvers.google-dot]
address = "8.8.8.8:853"
protocol = "dot"
```
