### ISSUE TITLE
Inverting of response-blocklist-ip feature request

### ISSUE THREAD

**Issue by jasonwei23** [folbricht/routedns#343]
By adding `invert=true` attribute to make the response only accept ip-address in target list.
```
[groups.cloudflare-blocklist]
type              = "response-blocklist-ip"
resolvers         = ["cloudflare-dot"]
blocklist-source  = [
  {invert = true, source = "/path/to/accpet-list.txt"},
]
```

**Comment by folbricht** [comment]
I couldn't easily do it on a per-list basis, but instead added a flag to the blocklist itself

```toml
[groups.cloudflare-blocklist]
type              = "response-blocklist-ip"
resolvers         = ["cloudflare-dot"]
inverted = true
blocklist-source  = [
  {source = "/path/to/accpet-list.txt"},
]
```
There's an implementation of that on the `issue-343` branch. Can you see if that works for you?  You may also want to set `filter = true` to strip the responses rather than block if a single IP is not on the list. This also now exists on `response-blocklist-name` so if you want to try that as well.
