### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by marcelloinfoweb** [folbricht/routedns#412]
How do I disable IPv6 or how do I know it's disabled?

**Comment by folbricht** [comment]
That depends on the OS you're using. Why are you disabling IPv6, is there an issue with routedns?

**Comment by marcelloinfoweb** [comment]
> That depends on the OS you're using. Why are you disabling IPv6, is there an issue with routedns?

I want to disable it because my ISP doesn't provide it and it also improves latency

**Comment by folbricht** [comment]
There is no global IPv6 switch, but a router can answer AAAA queries locally so they never reach an upstream:

```toml
[groups.static-nodata]
type  = "static-responder"
rcode = 0

[routers.router]
routes = [
  { type = "AAAA", resolver = "static-nodata" },
  { resolver = "upstream" },
]
```

`example-config/walled-garden.toml` shows the same pattern.

Separately, listeners take `ip-version = 4` if the goal is to only listen on IPv4.

Closing, since this is configurable rather than a code change.
