### ISSUE TITLE
Ability to rate-limit traffic (RRL)

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#43]
With all the DDOS attacks going on, it might be a good idea to see if a rate-limiting option is fiable.

There some good write-ups here:
https://github.com/coredns/rrl
https://kb.isc.org/docs/aa-00994

But I think for a caching-resolver it could be easy to just define per IP/Subnet/Network (both traffic from client and to forwarder/target-dns-server) the following:

- Maximum Queries/Responses per time/windowed-period (rolling)
  - This would include Return-Codes as well
- Log-only option, so no rate-limiting, but logging when thresholds/limits are hit
- Configurable response/mitigation (Drop, NXDOMAIN, NODATA etc)
  - Drop being default (?)
- Optional: Boost option, to overuse rate-limit for a particular period after limit is hit

**Comment by folbricht** [comment]
If I understand it correctly, this is to avoid the UDP listener being abused with spoofed client IPs. The idea is to rate-limit responses going to the same IP or network.

Wouldn't a query rate-limiter work as well in this case?

**Comment by cbuijs** [comment]
Completely, and indeed that was actually my suggestion and not clear from the original ticket :-).

**Comment by folbricht** [comment]
The `issue-43` branch now has a basic implementation that uses a fixed window for now.

```toml
[groups.cloudflare-rrl]
type = "rate-limiter"
resolvers = ["cloudflare-dot"]
requests = 0   # Number of requests allowed per time period
window = 60    # Number of seconds in the time period, default 60
prefix4 = 24   # Prefix length for identifying an IPv4 client, default 24
prefix6 = 56   # Prefix length for identifying an IPv6 client, default 56
```

It doesn't yet have a "limit-resolver" to direct queries based on hitting the limit. Not sure yet if necessary but it'd be nice to be able to control the response that way. Default response is to drop the request.
