### ISSUE TITLE
[Feature Request] HTTP/3 support in ODOH.

### ISSUE THREAD

**Issue by przemyslaw0** [folbricht/routedns#434]
I would like to use ODOH with QUIC because it's faster than TCP.

**Comment by LeonardWalter** [comment]
That is because the proxy and server you specified both don't support ODoH with quic. You need to set up your own proxy/server to use this. 

As far as I am aware, there are currently no other implementations available of ODoH that support HTTP3 / quic

**Comment by folbricht** [comment]
This already works. An ODoH resolver builds its connection to the proxy with the regular DoH client, and the `transport` option is passed through, so `transport = "quic"` runs the proxy leg over QUIC:

```toml
[resolvers.odoh-quic]
address   = "https://odoh.cloudflare-dns.com/dns-query"
protocol  = "odoh"
transport = "quic"
target    = "https://odoh.cloudflare-dns.com/dns-query"
```

It is documented in the ODoH resolver options as `transport` - `"tcp"` (default) or `"quic"` for the proxy connection.

Note this covers the hop from RouteDNS to the proxy, which is the one under your control. The proxy-to-target hop is up to the proxy operator.

Closing as done.
