### ISSUE TITLE
Support DNS 0x20

### ISSUE THREAD

**Issue by Anuskuss** [folbricht/routedns#441]
Basically make *everything* case-insensitive.

```toml
[groups.blocklist]
type      = "static-responder"
answer    = [ "IN A 0.0.0.0" ]

[groups.filter]
type               = "blocklist-v2"
blocklist-resolver = "blocklist"
blocklist-format   = "domain"
blocklist          = [ "example.com" ]
```

```bash
$ dig +short example.com
0.0.0.0
```

```bash
$ dig +short Example.com
23.192.228.80
```

**Comment by folbricht** [comment]
This should be done in https://github.com/folbricht/routedns/pull/445. Would be nice if you could confirm before I merge it

**Comment by Anuskuss** [comment]
#445 works but is it enough though? When I said *everything* I meant that literally. What about caches, client blocklists or routers? It all needs to be case insensitive.

**Comment by folbricht** [comment]
Using lowercase in the context of blocklists makes sense, but I'm not convinced that it should be done everywhere else. I'd rather not just change queries and responses in the other parts.

**Comment by folbricht** [comment]
Doing it for the cache does make sense. It's a little more tricky since we want to cache the response, but still restore the same case used in the query when responding, so I put that in a separate PR. https://github.com/folbricht/routedns/pull/447 should do that if you want to try it out

**Comment by Anuskuss** [comment]
I don't use the cache and wouldn't know how to test it. Maybe a good test would be to ask for `example.com` and `Example.com` and count the number of cached entries (should be 1).

Also this comment
https://github.com/folbricht/routedns/blob/28ece4d00b1d82eaa1bdfab827556e077662d4aa/cache_test.go#L55
should be clarified. This is **not** about *capital chars*, it's about *mixed-case*.
```
example.com == Example.com == eXample.com == EXAMPLE.COM
```

Besides `router`s (and maybe client names), is there anything other that needs to be case-sensitive? Maybe MAC addresses?

**Comment by folbricht** [comment]
MAC addresses are parsed as hex already so those don't need to change. And routers use regexes, meaning they can already deal with this. In fact, one could use a router to block all use of capitals in queries (or handle them in some other way).

**Comment by Anuskuss** [comment]
> And routers use regexes, meaning they can already deal with this. In fact, one could use a router to block all use of capitals in queries (or handle them in some other way).

Both can't simultaneously be true. I hope you don't mean I have to do something like this?

```toml
[routers.router]
routes = [
    { resolver = "block", name = '^[Pp][Oo][Rr][Nn]\.[Cc][Oo][Mm]\.$' }
]
```

If you don't wanna break backwards-compatibility (which to be honest I don't think anyone in the world is using upper-case here) or don't wanna take away the ability to "block all use of capitals in queries" (which I don't think is particularly useful), then you could always just introduce `iname`. Which again I dislike because I would assume that if I block `porn.com` my kids shouldn't be able to access it via `pOrN.cOm`.

**Comment by folbricht** [comment]
Matching case insensitive:
```toml
[routers.router]
routes = [
    { resolver = "block", name = '(?i)porn\.com\.$' }
]
```

Blocking anything that uses caps:
```toml
[routers.router]
routes = [
    { resolver = "block", name = '^.*[A-Z].*$' }
]
```
