### ISSUE TITLE
Cache Prefetch Feature

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#47]
To keep ahead of the curve, prefetching/refreshing particular records in cache before they get expired can potentional keep things speedy.

- Start prefetching at a particlar percentage of TTL expired
  - Default: 90%
- Cached records should have at least a minimal number of hits to be concidered for prefetching
  - Either a static number, default 3, or hits per time-unit (3 per minute for example)

Optional:
- Only prefetch when idle (like low number of queries, or CPU usage below percentage)

Additionally:
- Keep stale records for a definable time-period when prefetching cannot fetch a fresh copy (internet-connection gone for example), by extending the TTL by a definable number
  - Default: 120 seconds

Prefetching means getting a fresh copy before expiration and renewing the TTL.

**Comment by cbuijs** [comment]
I remembered I saw this one before:
https://coredns.io/plugins/cache/

**Comment by charlieporth1** [comment]
I like this feature. I think this should be next

**Comment by cbuijs** [comment]
Gentle nudge.

**Comment by charlieporth1** [comment]
@folbricht what would be the best way to implement this? The DNS resolving part is pretty simple because it's already included in the code. My guess would be a polling frequency in seconds compared to the records ttl set to a time remaining expiry percent. 

You could do it 2 ways a TTL prefetch element 

Which could look like this 
```toml
[cache-prefetch]
cache-ttl-polling-check-interval=60 # this would be in seconds as ttls are in seconds
min-record-time-remaining-percent=90 # this would be a percent based on the TTL time left with a check for next polling interval and if the next polling interval is would result in an expired record do the prefetch anyway.
cache-resolver=<cache to perform prefetch on> 
prefetch-resolver=<any cache resolver>
polling-record-size=1000 # which would be a record polling limiter an optional parameter for caches that are to large for the computer
```
Or we could add those parameters to the existing cache element minus the resolvers

**Comment by charlieporth1** [comment]
@folbricht @cbuijs I've got most of the prefetching code written out but I can't seem to get it to refetch the query which is something due to my inexpensive with routedns and go
If either one of you wants to take a look at it its on the branch `prefetch-feature` 
I get this error
```
TRAC[0122] cache err prefetch                            err="query for 'short-ttl-record.dns.test.ctptech.dev.' timed out"
```
FYI right now its logging more than it should only for debugging purposes documentation and comments will be added as a part of the release.
@folbricht Have a good Canada day and don't work too hard ;)

**Comment by folbricht** [comment]
@charlieporth1 No more Canada Day for me, different country.

So wrt prefetch, one thing we should make sure of is that only records that have recently been requested by a client should be considered for prefetch. If we refreshed everything in the cache, no records would ever be removed and the cache just keeps growing as it never forgets anything. What that means is that every record in the cache should have an additional attribute "this was recently fetched by a client". With that, prefetch can then decide what records to refresh (and reset the attribute).

With that, one could go further and perhaps count how often a record is requested by clients and refresh those more often, or implement a threshold like "only records that were requested N times in the last X seconds are prefetched".

It doesn't look like your branch has been pushed btw, there's only one commit and that doesn't yet touch the cache itself.

**Comment by folbricht** [comment]
Oh, btw as for implementation, a simpler (but perhaps less flexible) way to achieve a prefetch would be a new element that we could put in front of the cache. Imagine we don't change anything about the cache itself, but we had a "cron" element that could be configured to issue a number of queries on a schedule. So you could configure a set of records and have them queries every X seconds. Then if this element is put behind a cache, it'd keep those records refreshed since they get queried through the cache.

**Comment by cbuijs** [comment]
> Oh, btw as for implementation, a simpler (but perhaps less flexible) way to achieve a prefetch would be a new element that we could put in front of the cache. Imagine we don't change anything about the cache itself, but we had a "cron" element that could be configured to issue a number of queries on a schedule. So you could configure a set of records and have them queries every X seconds. Then if this element is put behind a cache, it'd keep those records refreshed since they get queried through the cache.

How would it now what is in cache? Or does it track via a separate table? Seems to be "double up" maybe.

**Comment by cbuijs** [comment]
> @charlieporth1 No more Canada Day for me, different country.
> 
> So wrt prefetch, one thing we should make sure of is that only records that have recently been requested by a client should be considered for prefetch. If we refreshed everything in the cache, no records would ever be removed and the cache just keeps growing as it never forgets anything. What that means is that every record in the cache should have an additional attribute "this was recently fetched by a client". With that, prefetch can then decide what records to refresh (and reset the attribute).
> 
> With that, one could go further and perhaps count how often a record is requested by clients and refresh those more often, or implement a threshold like "only records that were requested N times in the last X seconds are prefetched".
> 
> It doesn't look like your branch has been pushed btw, there's only one commit and that doesn't yet touch the cache itself.

Yeah, for sure. Only cached records will come in play. And they will expire if not queried in a particular time-frame. I think this is good reading to get some ideas:

https://coredns.io/plugins/cache/

**Comment by folbricht** [comment]
> > Oh, btw as for implementation, a simpler (but perhaps less flexible) way to achieve a prefetch would be a new element that we could put in front of the cache. Imagine we don't change anything about the cache itself, but we had a "cron" element that could be configured to issue a number of queries on a schedule. So you could configure a set of records and have them queries every X seconds. Then if this element is put behind a cache, it'd keep those records refreshed since they get queried through the cache.
> 
> How would it now what is in cache? Or does it track via a separate table? Seems to be "double up" maybe.

It wouldn't, it's just a way to ensure records are queried regularly and therefore be kept fresh in the cache. It's a pretty static solution since it requires pre-defining which records need to be kept updated.

**Comment by charlieporth1** [comment]
@folbricht would it be static records that are kept updated or frequently queried. I think frequently queried would be better because of flexibility. You could count the times read from cache or queried from a resolver and have a user-defined number of x queries or more. I think you could avoid doubling up by adding an element to the cache group of `prefetch-resolver`
```toml
[groups.cloudflare-cached-with-prefetch]
type = "cache"
prefetch-resolver = "catch-prefetch"

[groups.catch-prefetch]
type = "catch-prefetch"
record-query-hits-min = 10 
tll-expiry-percent = 90 
```

**Comment by charlieporth1** [comment]
@folbricht I did similar to what you said but is a dynamic prefetch based on request hits. 
Let me know if this is ok if not np - I'm just excited to be learning go.

**Comment by cbuijs** [comment]
I like the simplicity of this: [Cache prefetch in BIND](https://kb.isc.org/docs/aa-01122)

**Comment by folbricht** [comment]
I looked at this a bit more and I do like the simplicity of the prefetch in BIND. There's a fundamental issue though, not just with that solution but with all of them. Since routedns is forwarding to a recursive resolver, it doesn't normally get the real TTL, but the TTL from the upstream cache.

So for example we send a query for example.com to upstream and get a TTL of 60 in the response. Now after lets say 50s, prefetch will re-query example.com to keep the record fresh in the cache. The issue is though that this new response will not have a TTL of 60 again, but insteas just 10. So we didn't gain anything by querying again before the TTL expired upstream. We would always have to wait for records to expire out of the upstream cache before prefetching.

It may be possible to work around this using the BIND algorithm, but extending the TTL in the local cache by the "Trigger" amount. That way the record remains valid in the local cache, even though it has expired upstream.

**Comment by folbricht** [comment]
I implemented a draft feature on the `prefetch-3` branch. This functions very similar to what is described in https://kb.isc.org/docs/aa-01122, without any workarounds for upstream caches at this point. It'd be good to see how this works as-is first.

It's simple enough to be integrated into the cache itself and is configured like so:
```toml
[groups.cloudflare-cached]
type = "cache"
resolvers = ["cloudflare-dot"]
cache-prefetch-trigger = 10   # Prefetch when the TTL has fallen below this value
cache-prefetch-eligible = 20  # Only prefetch records if their original TTL is above this
```
