### ISSUE TITLE
Ability to block based on client-ip

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#57]
Basically what it says in the subject.

Same capabilities as `blocklist-response-ip` (except filtering), but then when `client-ip` is a match on:
- IP-Address/CIDR
- Match against Geoname-ID of the Client-IP

The `resolvers` and `blocklist-resolver` (as in `blocklist-response-ip`) are needed:
- `resolvers`: when no match
- `blocklist-resolver`: do match
  - When no `blocklist-resolver` but there is a match: default-action is either `REFUSED` or `DROP` (See below)
  
A `DROP` action might be needed besides the existing ones:
- When reqeuest is UDP: Drop request enterily
- When request is TCP: TCP-Reset (RST) connection and drop request entirly
  - Might need to cleanup TLS/SSL stuff

**Comment by folbricht** [comment]
There's now a `client-blocklist` element on the issue-57 branch. It supports the same kind of options and lists as response-blocklist-ip, namely CIDR and location lists. This does not yet allow a "drop" as this will need some more work in many of the other groups. Perhaps, rather than adding this to the blocklist itself, I add a dead-end element. Though dropping should probably be the default behavior of the client blocklist

**Comment by cbuijs** [comment]
Works as-is as expected. Looking forward to the drop functionality!

**Comment by folbricht** [comment]
There's now a new `drop` resolver that terminates a pipeline. Can be combined with the client-blocklist like so:

```toml
[groups.cloudflare-blocklist]
type                = "client-blocklist"
resolvers           = ["cloudflare-dot"]
blocklist-resolver  = "drop"
blocklist           = [
  '157.240.0.0/16',
]

[groups.drop]
type = "drop"
```

As for the default response from client-blocklist, I'm thinking REFUSED might be a reasonable option.
