### ISSUE TITLE
Persistent lists when using URL as source

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#67]
Would it be possible to have lists (`source`) that are retrieved via URL, to be persistent?

E.g. when RouteDNS restarts, it takes a local (previous downloaded) copy that is not expired yet (according the `*-refresh` parameter)?

It shaves off some seconds from the loading-time, but also when there are connectivity issues, the "last version" can be still be active/loaded, potentially protecting against unfiltered traffic due to it.

**Comment by folbricht** [comment]
Should be doable, perhaps once it supports named lists in the config. It'd be a local cache that could be used on startup and updated during refresh.

**Comment by cbuijs** [comment]
Yes please!

**Comment by folbricht** [comment]
@cbuijs There's now a first implementation of this on the issue-67 branch. All that should be needed is adding the `cache-dir` option to the remote HTTP lists like so:

```toml
[groups.cloudflare-blocklist]
type = "blocklist-v2"
resolvers = ["cloudflare-dot"]
blocklist-refresh = 86400
blocklist-source = [
   {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/routedns.blocklist.domain.list", cache-dir = "/var/tmp"},
   {format = "regexp", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/routedns.blocklist.regexp.list", cache-dir = "/var/tmp"},
]
```

This will cache the content to disk on every load, and use it (if available) at startup. That should improve the startup times a lot if you have many lists.
