### ISSUE TITLE
Define interfaces when forward DNS query to upstream servers

### ISSUE THREAD

**Issue by astrataro** [folbricht/routedns#74]
Hi,

I have multiple network interfaces on my router, and I hope to use different interfaces when routedns forwards DNS query to upstream servers. For some reason, I prefer not to use a static route table but to define the interfaces to be used for each upstream resolver in routedns configuration. For example:

```
[resolvers.cloudflare-doh]
address = "https://1.1.1.1/dns-query"
protocol = "doh"
interface = "192.168.0.1"

[resolvers.google-dot]
address = "dns.google:853"
protocol = "dot"
interface = "172.16.0.1"
```

**Comment by folbricht** [comment]
@astrataro Didn't have time to get it into all resolvers, but I put it into the DoH resolver (TCP) for now to test it out. Would you be able to give it a try before I add that to the others and update docs? It's on the `issue-74` branch at the moment and the config looks like this:

```toml
[resolvers.cloudflare-doh-quic]
address = "https://cloudflare-dns.com/dns-query"
protocol = "doh"
local-address = "192.168.1.123"
```

Note: `interface` can be a little ambiguous since it could refer to the network interface name, so I went with `local-address`
