### ISSUE TITLE
fail to start when setting as the only one local DNS resolver with URL blocklists

### ISSUE THREAD

**Issue by zhmars** [folbricht/routedns#81]
## Describe

Hi, thanks for the great project.

I got a error when starting routedns. And it disappear if I add other nameservers to `resolv.conf`. For example, `nameserver 223.5.5.5`. 
```
Error: default: Get "https://raw.githubusercontent.com/zhmars/misc/master/cn_domain.txt": dial tcp: lookup raw.githubusercontent.com: Temporary failure in name resolution
```

## Reproduce

- Remove extra resolvers from `/etc/resolv.conf`

```conf
# resolv.conf
nameserver 127.0.0.1
```

- Run `routedns -l 5 config.toml` with

```toml
# config.toml

[listeners.local-udp]
address = ':53'
protocol = 'udp'
resolver = 'default'

[groups.default]
resolvers = ['dns-default']
type = 'blocklist-v2'
blocklist-resolver = 'dns-cn'
blocklist-refresh = 86400
blocklist-source = [
  {format = 'domain', source = 'https://raw.githubusercontent.com/zhmars/misc/master/cn_domain.txt'},
]

[groups.dns-default]
type = 'fail-rotate'
resolvers = ['cloudflare-dot']

[groups.dns-cn]
type = 'fail-rotate'
resolvers = ['alidns-dot']

[resolvers.alidns-dot]
address = '223.5.5.5:853'
protocol = 'dot'

[resolvers.cloudflare-dot]
address = '1.1.1.1:853'
protocol = 'dot'
```

## Environment

- OS: Arch Linux

**Comment by folbricht** [comment]
Thanks for the report. This is an interesting issue. Didn't think of that when I added the remote blocklists feature. What's happening here is that the initial blocklist is loaded at startup, before RouteDNS' listeners are up. So it tries to resolve raw.githubusercontent.com and fails since there isn't a working resolver on the machine yet. That's why there's a `bootstratp-address` option for resolvers, but that doesn't exist for blocklists.

A few possible solutions:
1) Perhaps an option to lazy-load the blocklists, not load at startup but a configurable time after. The only reason it's currently loaded at startup is that it'll flag any config problems immediately, rather than later in the logs
2) Add a bootstrap address option, similar to resolvers. Don't particularly like this one since those server IPs are a whole lot more volatile than those of DNS servers
3) Option to specify a remote reosolver to use when looking up the blocklist hosts.
4) An option to specify another resolver to use, from the same config. This would allow the  use of DoT or other protocols. This could even be automatic, like always use the upstream resolver of a blocklist to lookup the host.

Thoughts?

**Comment by zhmars** [comment]
Thank you very much for your detailed explanation.

I would prefer a global fallback resolver for initial, similar to [bootstrap_dns](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) in AdGuardHome. And then we dont need any option to specify reosolvers for blocklist, allowlist, or other options support urls.

**Comment by cbuijs** [comment]
To stay consistent, I lean to the bootstrap_address option like with resolvers, but with a tweak to specify a resolver defined in routedns instead, this gives the most flexibility.

**Comment by folbricht** [comment]
Yes, I'm leaning towards using one of the defined resolvers as well. This is also a good chance to address https://github.com/folbricht/routedns/issues/56 at the same time. Just thinking if this should be a global setting for all internal name resolutions, or individual per entity.

**Comment by cbuijs** [comment]
Having an global option for all internal resolving should be fine, with three options:

- Use system resolvers (resolv.conf)
- Use a resolver defined in routedns config.
- None (to block/prevent any query/requests leakage when needed).

I still like the idea on top of above to be able to select a resolver defined in routedns config to override the global one, to be able to make it air-tight and have full control when needed.

**Comment by folbricht** [comment]
Given the configuration complexity, I think one global bootstrap resolver config is best here. It would default to using the system, could (ideally) be set to any resolver in the config. It'd be nice to be able to set it to groups too (especially the static responder) but this might be difficult since there could be un-resolvable dependencies in that case.

**Comment by folbricht** [comment]
There's a first implementation of this on the `issue-81` branch. @zhmars If you want to give it a try. All you should need is build RouteDNS from the branch and add something like this to your configuration:
```toml
[bootstrap-resolver]
address = "1.1.1.1:853"
protocol = "dot"
```
You can use whatever resolver protocol/server you want to use of course.
