### ISSUE TITLE
Can only use a "router" as resolver from "listeners", not from "groups".

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#9]
Subject says it all, when refering to a "router" from a "group" I get this error message:

`Error: group 'blocklist2' references non-existant resolver or group 'router`

This is the complete message, seems to be truncated (missing apastrophe at the end).

**Comment by folbricht** [comment]
That's a limitation of the config parser (not new). The code could handle it just fine. Can take another look at supporting this.

**Comment by cbuijs** [comment]
Awesome. I now create an extra listener pointing to the router and use that in a group as resolver as work around. Works flawless, but is... well... ugly? :-)

**Comment by folbricht** [comment]
I might just turn routers into another group element, while staying backwards compatible. Btw, I really dislike the name `group`, poor choice at the time but couldn't come up with anything better. Going to change that if I find a more descriptive term.

**Comment by cbuijs** [comment]
Is there a real reason to keep the names before the first-dot other then clarity (not functionally)? Why not just have the user name it however it wants and configure it function? (I didn't check, just wondering)

But turning routers into groups works for me just nicely too :-)

**Comment by folbricht** [comment]
Those are needed to load the elements into an array internally. Pretty much everything in a config is a "resolver" type, except the listeners. This was my first experiment with toml configs, going to see if there's something that would simplify the naming a bit.

**Comment by folbricht** [comment]
Whipped something up for it. Not exactly pretty but seems to do the job. Still un-merged on https://github.com/folbricht/routedns/tree/issue-9 since I still need to update the docs accordingly. The example below works now. It goes like this:

Listeners->Blocklist->Router->Cache->Resolver

```toml
[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[resolvers.google-dot]
address = "8.8.8.8:53"
protocol = "udp"

[groups.cloudflare-cached]
type = "cache"
resolvers = ["cloudflare-dot"]

[routers.router1]
routes = [
  { name = '\.twitter\.com\.$', resolver="cloudflare-cached" },
  { name = '\.facebook\.com\.$', resolver="cloudflare-cached" },
  { resolver="google-dot" }, # default route
]

[groups.my-blocklist]
type = "blocklist"
resolvers = ["router1"]
format    = "domain"
blocklist = [
  '.evil.com',
]

[listeners.local-udp]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "my-blocklist"

[listeners.local-tcp]
address = "127.0.0.1:53"
protocol = "tcp"
resolver = "my-blocklist"
```

Please give it a try with a more complex configuration. I only used a small set of config files.
