### ISSUE TITLE
Block based on Return-Code (RCODE)

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#96]
Just wondering how difficult it is to add a response group based on return-code, either the number or text-base version.

See here:
[Return Codes](https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6)

For example you could generate a more appropriate response on NXDOMAIN by facilitating an IP-Address pointing to a landing-page or try another query against another DNS server.

**Comment by folbricht** [comment]
It might be best to have some sort of response router here, one that can "retry" a query if the response matches certain conditions. Like so
```toml
[routers.router1]
type="response"
resolver=["google-udp"]
routes = [
  { rcode = 2, resolver="static-1" }, # SERVFAIL
  { rcode = 3, resolver="static-2" }, # NXDOMAIN
]
```

It could also be done much simpler, without the multi-routing piece

```toml
[groups.response-reroute]
type = "response-reroute"
resolvers = ["google-dot"] # Default
rcode = 3 # NXDOMAIN
reroute-resolver = "static-1" # Some static response
```
